# No Tomcat scraper doesn't need HTTP
spring.main.web-application-type=none

# Same DB connection
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:SDP}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:admin}

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
logging.level.org.apache.kafka.clients=ERROR
logging.level.org.apache.kafka.common=ERROR
logging.level.org.springframework.kafka.listener=ERROR
spring.kafka.consumer.properties.max.poll.records=500000

# Give Chromium room to breathe
#JAVA_OPTS=-Xmx600m -Xms300m