spring.application.name=Test

# ------------------------------
# SPRING DATASOURCE
# ------------------------------
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:SDP}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:admin}
#spring.datasource.driver-class-name=org.postgresql.Driver

# ------------------------------
# JPA / HIBERNATE
# ------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ------------------------------
# SERVER
# ------------------------------
server.port=5000

# ------------------------------
# SCHEDULER LOGGING
# ------------------------------
logging.level.org.springframework.scheduling=INFO