spring.application.name=SDP-TezTap

# ------------------------------
# SPRING DATASOURCE
# ------------------------------
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:SDP}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:admin}

# ------------------------------
# JPA / HIBERNATE
# ------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ------------------------------
# JWT
# ------------------------------
# your-very-long-secret-key-at-least-256-bits-long-here!!
app.jwt.secret=${JWT_KEY:SxyexhxcWb6PdaGMD0RtqfcfUZWIarcT}
app.jwt.expiration-ms=86400000

# ------------------------------
# SERVER
# ------------------------------
server.port=5000

# ------------------------------
# SCHEDULER LOGGING
# ------------------------------
logging.level.org.springframework.scheduling=INFO

# ------------------------------
# SPRING SECURITY
# ------------------------------
#logging.level.org.springframework.security=TRACE
#logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
#logging.level.org.springframework.security.access=TRACE