# No Tomcat ? scraper doesn't need HTTP
spring.main.web-application-type=none

# Same DB connection
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:SDP}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:admin}

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_SERVERS}

# Give Chromium room to breathe
#JAVA_OPTS=-Xmx600m -Xms300m